name: CI1
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    name: Unit Tests
    timeout-minutes: 30
    defaults:
      run:
        working-directory: Composer
    outputs:
      test-chunks: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}
      test-chunk-ids: ${{ steps['set-test-chunk-ids'].outputs['test-chunk-ids'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5
      #- name: Restore yarn cache
      #  uses: actions/cache@v2.1.2
      #  with:
      #    path: ~/.cache/yarn
      #    key: ${{ runner.os }}-yarn-new-${{ hashFiles(format('{0}{1}', github.workspace, '/Composer/yarn.lock')) }}
      #    restore-keys: |
      #      ${{ runner.os }}-yarn-new-
      - name: Clear global yarn cache
        run: yarn cache clean
      - name: yarn --update-checksums
        run: yarn --update-checksums
      - name: yarn build:dev
        run: yarn build:dev
      - id: set-test-chunks
        name: Set Chunks
        run: echo "::set-output name=test-chunks::$(npx jest --listTests --json | jq -cM '[_nwise(length / 2 | floor)]')"
      - id: set-test-chunk-ids
        name: Set Chunk IDs
        run: echo "::set-output name=test-chunk-ids::$(echo $CHUNKS | jq -cM 'to_entries | map(.key)')"
        env:
          CHUNKS: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}
  test:
    runs-on: ubuntu-latest
    name: test (chunk ${{ matrix.dir }})
    needs: [setup]
    strategy:
      fail-fast: true
      matrix:
        dir: ${{fromJson(needs.setup.outputs['test-chunk-ids'])}}
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - name: jest
        run: echo $CHUNKS | jq '.[${{ matrix.dir }}] | .[] | @text' | xargs npx jest
        env:
          CHUNKS: ${{ needs.setup.outputs['test-chunks'] }}
